#!/bin/bash
#HQ-SRV

mkdir /mnt/demo

mount /dev/sr0 /mnt/demo

apt-get install lamp-server -y

cp /mnt/demo/web/index.php /var/www/html/
cp /mnt/demo/web/logo.png /var/www/html/

sed -i 's/$username = "user";/$username = "webc";/' /var/www/html/index.php
sed -i 's/$password = "password";/$password = "P@ssw0rd";/' /var/www/html/index.php
sed -i 's/$dbname = "db"/$dbname = "webdb"/' /var/www/html/index.php

systemctl enable --now mariadb

mariadb -u root -e "CREATE DATABASE webdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci; CREATE USER 'webc'@'localhost' IDENTIFIED BY 'P@ssw0rd'; GRANT ALL PRIVILEGES ON webdb.* TO 'webc'@'localhost'; FLUSH PRIVILEGES; EXIT;"

systemctl enable --now httpd2

#mariadb -u webc -p webdb < /mnt/demo/web/dump.sql
exit 0
